### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by wooorm** [hrzafer/hunspell-tr#1]
Hey, first of all: great work! Second, I just downloaded an (i believe) by this library generated [open-office extension](http://extensions.openoffice.org/en/project/turkish-spellcheck-dictionary). And I’m missing information regarding which license the dictionary is distributed with.

Am I correct in guessing it’s MIT, just like your other tools?

P.S., I also found that the latest version is not [downloadable](http://extensions.openoffice.org/en/project/turkish-spellcheck-dictionary) (click the big green button on the right).

**Comment by wooorm** [comment]
@hrzafer Ping!

**Comment by hrzafer** [comment]
Hi, sorry for the very late response. Some how I didn't know about this issue before the ping. 
Yes, the license is MIT. And the latest version (1.3) is downloadable. I also use the same dictionary with [this](https://addons.mozilla.org/en-US/firefox/addon/t%C3%BCrk%C3%A7e-imla-denetimi/). By the way, the dictionary is good for spellcheck but not so good for getting suggestions. This is on my to do list, but I didn't find a chance to work on this project lately.

**Comment by wooorm** [comment]
Thanks for getting back to me, @hrzafer, for some reason I missed the license file in this repo. :anguished: 

Thanks again!
