### ISSUE TITLE
words.txt

### ISSUE THREAD

**Issue by skeet70** [hrzafer/hunspell-tr#2]
Is there a copy of the words.txt dictionary that you used with this tool to generate the LibreOffice extension? I see in Program.cs that it's looking for one in a data directory, but can't find that file anywhere.

**Comment by hrzafer** [comment]
Hi, sorry for very late response. For some reason I didn't get any notification e-mail for this issue. I just saw it. You can download the related files from [here](https://www.dropbox.com/s/xb37j9gt9zeypit/data.zip?dl=1)
